
server:
  port: 8778

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration