eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888

spring:
  application:
    name: Userverwaltung-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:8889/mydb
    username: root
    password: 12345
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration